name: nestjs testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - test
          - staging
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env.${{ matrix.env }}
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env.${{ matrix.env }}
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env.${{ matrix.env }}
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env.${{ matrix.env }}
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env.${{ matrix.env }}
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env.${{ matrix.env }}
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env.${{ matrix.env }}
          echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> .env.${{ matrix.env }}

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        env:
          NODE_ENV: ${{ matrix.env }}
        run: |
          export $(cat .env.${{ matrix.env }} | xargs)
          yarn test

      - name: Clean up .env file
        run: rm .env.${{ matrix.env }}
        if: always()
